version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Add any environment variables here
      # - EXAMPLE_VAR=value
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
